### ISSUE TITLE
feat: Access Control logic to handle badge ownerships

### ISSUE THREAD

**Issue by RafaDSan** [blockful-io/trustful-zuzalu#3]
### Describe the Feature Request

We have three main elements in the project, `root`, `manager` and `people`.  Each one of them have different accss privileges, where: 

- `root:`  The organization (Swaplace) that can `create` (a badge), `revoke` (a badge) and transfer onwership (Can transfer its privileges to another address)

- `manager`: The client that can `create` a badge for the `people` and do `event attests`
Obs: The `manager` can only be granted a badge from the `root`.

- `people`: the end consumer who is presencially at the event, who can gain a `bedge` from the `manager`

Basically: The `people` has to have a token `checkIn` given by the `Manager`. Therefore, it needs a validation to check this scenario. 
The `manager` has to have a `attestation` badge given by the `root`.  Therefore, it needs a validation to check this scenario. 
The `root` has to be verified to emmit a badge.

### Definition of Done

Use the [SchemaResolver.sol](https://github.com/ethereum-attestation-service/eas-contracts/blob/master/contracts/resolver/SchemaResolver.sol) to create the access control logic to handle the privileges access of the elements in order to have an automated validation.

- [x] Create auth roles for the dApp: Root, Manager, Villagers
- [x] Add an allowlist mapping that registers permissions
- [x] Verify permissions in the `attest(...)` hook

**Comment by 0xneves** [comment]
Since the idea is not handling backend or looping through multiple indexing solutions to track back all history of attestations just to validate a role, we are opting to use AES resolver solution which is basically a hook that we can configure a smart contract that works as an access control without interfering with the attestation emission.

**Comment by 0xneves** [comment]
The solution is being worked on trustful-zuzalu-contracts in [here](https://github.com/blockful-io/trustful-zuzalu-contracts/issues/5)
