### ISSUE TITLE
Feat: Frontend integration with smart contract functions

### ISSUE THREAD

**Issue by RafaDSan** [blockful-io/trustful-zuzalu#40]
1. Create each schema for the latest `resolver.sol` smart contract deployed
2. [manager](https://optimism.easscan.org/schema/view/0xd130b9591f22bb9653f125ed00ff2d7d88b41d64acfd962365b42fe720c295aa)
3. [villager](https://optimism.easscan.org/schema/view/0xcb74f95269512c5cb95c9f854a8ec8fe015d453f1bbff52d83ffd894dfec1883)
4. [registry_attest](https://optimism.easscan.org/schema/view/0x157df2f42e66b3dc2fd354354cb3d678789b258a8aa5a5493d6c3b75ab003a69)
5. [registry_response_attest](https://optimism.easscan.org/schema/view/0x440a07d9a96ab2f16f2e983582f5331bd80c7c9033d57c784c052619b868a9c2)
6. Create (send) the `attestation` for the schema in the `GiveBadgeSection.tsx` 2.1 - Confirm the correct creation of the attestation through the flow of the application

**Comment by 0xneves** [comment]
This was resolved by some PR that we long forgot xD
