### ISSUE TITLE
chores: requesting information from Zuzalu

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/trustful-zuzalu#48]
What do we need to know?

- [x] Assets to have refs for the design of the pages
- [x] All badges they want to emit
- [x] Will they want to assign managers during the event period themselves? ( the ones that can check-in users)
- [x] Will they want to have full control over the Resolver?
- [x] Will they want to create new badges during the event?
- [ ] Will they want a vanity address for their contract? (max 12 decimals)

**Comment by danimim** [comment]
Hey, gm!

Heads up on it: 
1) [Assets to have refs for the design of the pages](https://www.canva.com/design/DAGJ5sLbHHo/qkWFog2Vj5ca-6dhHCCN8A/edit)
2) All badges they want to emit:

- changed my mind about X, phrasing has to be confirmed
- disagreed with somebody on stage
- create session on Zuzalu.city
- check in proof of personhood
- check out time elapsed
- write on Zuzagora
- voted on significant poll
- early contributors
- one for each week? With theme of week
- volunteer during event
- start a new club
- host a discussion

The rest of the questions I'm waiting for a response. 
Thanks Mr. Neves

**Comment by 0xneves** [comment]
Another very importante questions, who will do the checkout? the user or a manager of zuzalu?  Also important, will managers of Zulalu be allowed to force checkout users?

**Comment by 0xneves** [comment]
What are the comments we should use in this section?
![image](https://github.com/user-attachments/assets/b921c5d3-a562-489a-97d8-2480c77d1079)

**Comment by danimim** [comment]
> What are the comments we should use in this section? ![image](https://private-user-images.githubusercontent.com/90667119/348058514-b921c5d3-a562-489a-97d8-2480c77d1079.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3Nzk2MDcsIm5iZiI6MTcyMDc3OTMwNywicGF0aCI6Ii85MDY2NzExOS8zNDgwNTg1MTQtYjkyMWM1ZDMtYTU2Mi00ODlhLTk3ZDgtMjQ4MGM3N2QxMDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDEwMTUwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlOTdjODMzZGY0MDBmNDhjNmNhYmIyNzRiNDczNTIxZmYxMjgzMWU3NDY2NmYyYTk2YWI1NWRmZmY4NTIyOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VhjUt5nxTABGfft4QkfzpwanSUcdgVH8Cej_S2drtQE)

**1) What is Trustful?**
_Trustful is a reputation aggregator system designed to match governance, participation, and efforts. Using the Ethereum Attestation Service (EAS) and a badge system, we can attest to specific participation and ensure that this on-chain information results in a scoring system. This system can be used for resource allocation, governance, and more._

**2) How does Trustful work in ZuVillage?**
_In ZuVillage, your interactions and contributions will be attested to and stored on-chain. This promotes dialogue, avoids echo chambers, and encourages active participation. In the future, this aggregated reputation can be used to benefit participants, providing them with recognition._

**3) What do you need to do now?**
- _Now that you have connected your wallet, you need to do the check-in.
- Your check-in badge will be your first badge, unlocking the creation of other badges.
- By interacting with the event, whether by disagreeing with someone, actively participating in talks, or creating sessions, you can create or attest to badges.
- This process builds your reputation, tied to your wallet, based on your interactions._

**Comment by danimim** [comment]
**More questions that may appear**

**What is the check out for?**
The check out badge confirms that you are ending your stay at ZuVillage Georgia. It will be used to calculate how long you lived in our ZuVillage, which will contribute to your ZuVillager reputation score. It also helps us keep track of how many people are currently present. Thank you for joining us at ZuVillage Georgia!

**What is the check out badge?**
The check out badge is an advanced reputation aggregator built by Trustful. Trustful aims to foster real connections and deep dialogues, facilitating check-in processes and enabling attestations of the quality of interactions and the convergence of ideas. By integrating Trustful into ZuVillage Georgia, Trustful aims to create an environment where reputation is defined and recognized based on the community's unique values, ensuring that members' contributions and interactions are duly valued. This first OP version for ZuVillage Georgia will focus on creating new Statement Badges and it will allow organizers and attendants of a Zuzalu pop-up village event to give badges to each other in recognition of their contributions and knowledge. This mobile-first version aims to enable the community to create its first badges, which members will later use to generate Reputation Scores.
