### ISSUE TITLE
feat: `Admin` item inside the menu with multiple actions

### ISSUE THREAD

**Issue by RafaDSan** [blockful-io/trustful-zuzalu#66]
Add the `Admin` item into the dropdown menu with the following items inside it:

- **Grant Role:** Make a dropdown menu to select the user's role
- **Revoke Role:** An action to remove the role of an user
- **Set Attestation Title:** Create a new name of an attestation
- **Set schema**: Make a dropdown menu to select who can operate in the schema (Manager, Villager, Attest or Reply)

**Comment by 0xneves** [comment]
Heads up, the manager should also be able to view the admin page. But the only function he can call is `setAttestationTitle`. In matter fact, only the manager can call this function, so the ROOT must always check in as manager if he wants to create new badges

**Comment by 0xneves** [comment]
I just realized that the titles are hardcoded into the dApp front-end. We need to cut this dependency and make it always check for new titles. I will create a new issue to implement a way to calculate that by calling the contract directly

**Comment by 0xneves** [comment]
fixed by #103
